project_name: 租租鸭app自动化接口测试

env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 肖朝鹏

# 域名1
host: http://dev.adminapi.zuzuya.cn
# 域名2，支持多个域名配置
app_host: https://dev.api.zuzuya.cn

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: True

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
# 支持同时发送多个通知，如多个，则用逗号分割， 如 1, 2
notification_type: 0
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False

# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置

# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=0576735857b406448ffb3feba889a5c619321614985b8d77a8d7428a3f30e9fd
  secret: SECd5dd9e8775867d72e12b6c01bf03922e889d7529543cdc31abcfd59cb4792e55
#  webhook:
#  secret:
# 数据库相关配置
mysql_db:
  # 数据库开关
  switch: True
  host: ob-4ns1d6jqa5mo.db.cloudob.cn
  user: admin
  password: 'Zzyadmin2023'
  port: 3306

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
wechat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22748687-fa3b-4e48-a5d7-0502cef422b4


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 重要的事情说三遍
email:
  send_user: Xzp <1340128837@qq.com>
  email_host: smtp.qq.com
  # 自己到QQ邮箱中配置stamp_key
  stamp_key: lhdwtrfckiiebaej
  # 收件人改成自己的邮箱
  send_list: 1340128837@qq.com

# 飞书通知
lark:
  webhook:



